import type {NextPage} from 'next'
import Head from 'next/head'
import {Header} from "../components/Header";

const Home: NextPage = () => {
  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>

        <Header/>
        <main>
          <h1 className="text-2xl text-red-500">
            TailwindCss
          </h1>
        </main>
      </div>
  )
}

export default Home
