import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";
import { Tabs } from "../components/Tabs";
import { fetchCategories } from "../utils/fetchCategories";
import { fetchProducts } from "../utils/fetchProducts";

type HomePageProps = {
  categories: Category[];
  products: Product[];
};

const Home = ({ categories, products }: HomePageProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="relative h-[200vh] bg-[#E7ECEE]">
        <Hero />
      </main>

      <section className="relative z-40 -mt-[100vh] min-h-screen bg-[#1B1B1B]">
        <div className="space-y-10 py-16">
          <h2 className="text-center text-4xl font-medium tracking-wide text-white md:text-5xl">
            New Promos
          </h2>
          <Tabs categories={categories} products={products} />
        </div>
      </section>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<
  HomePageProps
> = async () => {
  const categories = await fetchCategories();
  const products = await fetchProducts();
  return {
    props: {
      categories,
      products,
    },
  };
};
